---
- name: Validate and setup dynamic hosts
  hosts: localhost
  tasks:
    - name: Fail if no hosts provided
      fail:
        msg: "No hosts specified! Use the survey to enter target servers."
      when: runtime_servers == "unspecified"

    - name: Add dynamic hosts
      add_host:
        name: "{{ item }}"
        groups: mariadb_servers
        ansible_connection: ssh
        ansible_user: vagrant
      loop: "{{ runtime_servers.split(',') }}"

- name: Install Mariadb
  hosts: mariadb_servers
  become: true
  tasks:

    - name: Install dependencies (Debian)
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - mariadb
      when: ansible_os_family == "Debian"

    - name: Enable and start Mariadb (Debian)
      systemd:
        name: mariadb
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Install EPEL release (RedHat)
      yum:
        name: epel-release
        state: present
      when: ansible_os_family == "RedHat"

    - name: Add MariaDB YUM Repository (CentOS 7)
      yum_repository:
        name: MariaDB
        description: MariaDB Repository
        baseurl: http://yum.mariadb.org/10.5/centos7-amd64
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: yes
      when: ansible_os_family == "RedHat"

    - name: Install MariaDB Server (RedHat)
      yum:
        name: MariaDB-server
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable MariaDB service (RedHat)
      systemd:
        name: mariadb
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"
